# -*- coding: utf-8 -*-
"""Hand-curated trim cuts for the location_pool=trimmed branch (DLC-only short-AP curation,
Alaric 2026-06-15). Item-name denylists dropped in Trimmed, plus the armor set-collapse
non-representative pieces. Derived from the trimmed DLC pool + PvE tier list via codegen;
see er-trimmed-audit memory. Representative of each armor set = lowest er_code piece (the
head slot); non-rep pieces listed here are dropped in Trimmed so each kept set = 1 check."""

# Comedy junk: deliberately-bad items worth sparing from the curation scrub so a few
# "bad checks" survive -- bad checks are part of the spirit of AP (Alaric, 2026-06-17).
# Exact item_table names (verified 2026-06-17). Source for the junk_retention knob; the
# selection is comedy-weighted by construction because it is drawn from this set first.
# Extend freely with any item whose appearance in a chest is funnier than it is useful.
COMEDY_JUNK = frozenset({
    "Blood-Tainted Excrement",   # throwable dung -- the platonic bad check
    "Gold-Tinged Excrement",
    "Horn-Strewn Excrement",
    "Soiled Loincloth",          # F-tier "now you are naked and worse" armor
    "Toxic Mushroom",            # a "consumable" that poisons YOU
    "Dung Eater Puppet",
    "Fly Mold",
    "Raw Meat Dumpling",
    "Ash of War: No Skill",      # the joke ashes (now tiered F / D)
    "Ash of War: Kick",
    "Festering Bloody Finger",   # useless invasion item in a solo run
})


TRIM_CUT_WEAPONS = frozenset({
    "Ansbach's Longbow",
    "Bloodfiend's Sacred Spear",
    'Bonny Butchering Knife',
    'Chilling Perfume Bottle',
    'Deadly Poison Perfume Bottle',
    "Devonia's Hammer",
    'Golden Lion Shield',
    'Greatsword of Radahn (Light)',
    'Lamenting Visage',
    'Madding Hand',
    'Main-gauche',
    "Nanaya's Torch",
    'Repeating Crossbow',
    'Serpent Crest Shield',
    'Shield of Night',
    'Smithscript Spear',
    'Spiraltree Seal',
    'Spirit Glaive',
    'Spirit Sword',
    'Spread Crossbow',
    'Stone-Sheathed Sword',
    'Swift Spear',
    "Thiollier's Hidden Needle",
    'Tooth Whip',
    'Wolf Crest Shield',
})

TRIM_CUT_ARMOR = frozenset({
    "Ansbach's Attire",
    "Ansbach's Boots",
    "Ansbach's Manchettes",
    'Braided Arm Wraps',
    'Braided Cord Robe',
    'Caterpillar Mask',
    'Dryleaf Arm Wraps',
    'Dryleaf Cuissardes',
    'Dryleaf Robe',
    'Fang Helm',
    'Gloried Attire',
    'High Priest Gloves',
    'High Priest Hat',
    'High Priest Robe',
    'High Priest Undergarments',
    'Highland Attire',
    "Igon's Armor",
    "Igon's Gauntlets",
    "Igon's Helm",
    "Igon's Loincloth",
    'Imp Head (Lion)',
    'Iron Rivet Armor',
    'Iron Rivet Gauntlets',
    'Iron Rivet Greaves',
    "Thiollier's Garb",
    "Thiollier's Gloves",
    "Thiollier's Mask",
    "Thiollier's Trousers",
    "Wise Man's Mask",
})

TRIM_CUT_RUNES = frozenset({
    'Shadow Realm Rune [2]',
    'Shadow Realm Rune [3]',
    'Shadow Realm Rune [4]',
    'Shadow Realm Rune [5]',
})

TRIM_CUT_NAMES = TRIM_CUT_WEAPONS | TRIM_CUT_ARMOR | TRIM_CUT_RUNES

ARMOR_SET_NONREP = frozenset({
    "Alberich's Bracers",
    "Alberich's Robe",
    "Alberich's Trousers",
    'All-Knowing Armor',
    'All-Knowing Gauntlets',
    'All-Knowing Greaves',
    "Ansbach's Attire",
    "Ansbach's Boots",
    "Ansbach's Manchettes",
    'Aristocrat Boots',
    'Aristocrat Coat',
    'Aristocrat Garb',
    'Armor of Night',
    'Armor of Solitude',
    "Ascetic's Ankle Guards",
    "Ascetic's Loincloth",
    "Ascetic's Wrist Guards",
    'Astrologer Gloves',
    'Astrologer Robe',
    'Astrologer Trousers',
    "Azur's Glintstone Robe",
    "Azur's Manchettes",
    'Bandit Boots',
    'Bandit Manchettes',
    'Banished Knight Armor',
    'Banished Knight Armor (Altered)',
    'Banished Knight Gauntlets',
    'Banished Knight Greaves',
    'Battlemage Legwraps',
    'Battlemage Manchettes',
    'Battlemage Robe',
    'Beast Champion Gauntlets',
    'Beast Champion Greaves',
    'Black Knife Armor',
    'Black Knife Gauntlets',
    'Black Knife Greaves',
    'Black Knight Armor',
    'Black Knight Gauntlets',
    'Black Knight Greaves',
    'Blackflame Monk Armor',
    'Blackflame Monk Gauntlets',
    'Blackflame Monk Greaves',
    "Blaidd's Armor",
    "Blaidd's Gauntlets",
    "Blaidd's Greaves",
    'Bloodhound Knight Armor',
    'Bloodhound Knight Gauntlets',
    'Bloodhound Knight Greaves',
    'Bloodsoaked Manchettes',
    'Blue Cloth Vest',
    'Blue Festive Garb',
    'Blue Silver Bracelets',
    'Blue Silver Mail Armor',
    'Blue Silver Mail Skirt',
    'Braided Arm Wraps',
    'Braided Cord Robe',
    'Briar Armor',
    'Briar Gauntlets',
    'Briar Greaves',
    'Bull-Goat Armor',
    'Bull-Goat Gauntlets',
    'Bull-Goat Greaves',
    'Carian Knight Armor',
    'Carian Knight Gauntlets',
    'Carian Knight Greaves',
    'Chain Armor',
    'Chain Leggings',
    'Chain-Draped Tabard',
    'Champion Bracers',
    'Champion Gaiters',
    'Champion Pauldron',
    'Cleanrot Armor',
    'Cleanrot Gauntlets',
    'Cleanrot Greaves',
    'Cloth Garb',
    'Cloth Trousers',
    'Common Soldier Cloth Armor',
    'Common Soldier Gauntlets',
    'Common Soldier Greaves',
    "Commoner's Garb",
    "Commoner's Shoes",
    'Confessor Armor',
    'Confessor Boots',
    'Confessor Gloves',
    "Consort's Robe",
    "Consort's Trousers",
    "Corhyn's Robe",
    'Crucible Axe Armor',
    'Crucible Gauntlets',
    'Crucible Greaves',
    'Crucible Tree Armor',
    'Cuckoo Knight Armor',
    'Cuckoo Knight Gauntlets',
    'Cuckoo Knight Greaves',
    'Cuckoo Surcoat',
    "Dancer's Bracer",
    "Dancer's Dress",
    "Dancer's Trousers",
    'Death Knight Armor',
    'Death Knight Gauntlets',
    'Death Knight Greaves',
    'Depraved Perfumer Gloves',
    'Depraved Perfumer Robe',
    'Depraved Perfumer Trousers',
    'Dirty Chainmail',
    'Divine Beast Warrior Armor',
    'Divine Bird Warrior Armor',
    'Divine Bird Warrior Gauntlets',
    'Divine Bird Warrior Greaves',
    'Drake Knight Armor',
    'Drake Knight Gauntlets',
    'Drake Knight Greaves',
    'Dryleaf Arm Wraps',
    'Dryleaf Cuissardes',
    'Dryleaf Robe',
    'Duelist Greaves',
    "Eccentric's Armor",
    "Eccentric's Breeches",
    "Eccentric's Manchettes",
    'Elden Lord Armor',
    'Elden Lord Bracers',
    'Elden Lord Greaves',
    'Erdtree Surcoat',
    'Errant Sorcerer Boots',
    'Errant Sorcerer Manchettes',
    'Exile Armor',
    'Exile Gauntlets',
    'Exile Greaves',
    'Eye Surcoat',
    'Festive Garb',
    "Fia's Robe",
    'Finger Maiden Robe',
    'Finger Maiden Shoes',
    'Fingerprint Armor',
    'Fingerprint Gauntlets',
    'Fingerprint Greaves',
    'Fire Knight Armor',
    'Fire Knight Gauntlets',
    'Fire Knight Greaves',
    'Fire Monk Armor',
    'Fire Monk Gauntlets',
    'Fire Monk Greaves',
    'Fire Prelate Armor',
    'Fire Prelate Gauntlets',
    'Fire Prelate Greaves',
    'Foot Soldier Gauntlets',
    'Foot Soldier Greaves',
    'Foot Soldier Tabard',
    "Freyja's Armor",
    "Freyja's Gauntlets",
    "Freyja's Greaves",
    'Fur Leggings',
    'Fur Raiment',
    "Gaius's Armor",
    "Gaius's Gauntlets",
    "Gaius's Greaves",
    'Gauntlets',
    'Gauntlets of Night',
    'Gauntlets of Solitude',
    'Gelmir Knight Armor',
    'Gelmir Knight Gauntlets',
    'Gelmir Knight Greaves',
    'Gloried Attire',
    'Godrick Knight Armor',
    'Godrick Knight Gauntlets',
    'Godrick Knight Greaves',
    'Godrick Soldier Gauntlets',
    'Godrick Soldier Greaves',
    'Godskin Apostle Bracelets',
    'Godskin Apostle Robe',
    'Godskin Apostle Trousers',
    'Godskin Noble Bracelets',
    'Godskin Noble Robe',
    'Godskin Noble Trousers',
    'Gold Bracelets',
    'Gold Waistwrap',
    "Goldmask's Rags",
    'Gravebird Anklets',
    'Gravebird Bracelets',
    "Gravebird's Blackquill Armor",
    'Gravekeeper Cloak',
    'Greaves of Night',
    'Greaves of Solitude',
    'Guardian Bracers',
    'Guardian Garb (Full Bloom)',
    'Guardian Greaves',
    'Haligtree Crest Surcoat',
    'Haligtree Gauntlets',
    'Haligtree Greaves',
    'Haligtree Knight Armor',
    'Haligtree Knight Gauntlets',
    'Haligtree Knight Greaves',
    'High Page Clothes',
    'High Priest Gloves',
    'High Priest Robe',
    'High Priest Undergarments',
    'Highland Attire',
    'Highwayman Cloth Armor',
    'Highwayman Gauntlets',
    'Horned Warrior Armor',
    'Horned Warrior Gauntlets',
    'Horned Warrior Greaves',
    "Hoslow's Armor",
    "Hoslow's Gauntlets",
    "Hoslow's Greaves",
    "Igon's Armor",
    "Igon's Gauntlets",
    "Igon's Loincloth",
    'Iron Gauntlets',
    'Iron Rivet Armor',
    'Iron Rivet Gauntlets',
    'Iron Rivet Greaves',
    'Ivory-Draped Tabard',
    'Juvenile Scholar Robe',
    'Kaiden Armor',
    'Kaiden Gauntlets',
    'Kaiden Trousers',
    'Knight Armor',
    'Knight Gauntlets',
    'Knight Greaves',
    'Land of Reeds Armor',
    'Land of Reeds Gauntlets',
    'Land of Reeds Greaves',
    'Leather Arm Wraps',
    'Leather Armor',
    'Leather Boots',
    'Leather Gloves',
    'Leather Leg Wraps',
    'Leather Trousers',
    'Leather-Draped Tabard',
    "Leda's Armor",
    'Leyndell Knight Armor',
    'Leyndell Knight Gauntlets',
    'Leyndell Knight Greaves',
    'Leyndell Soldier Gauntlets',
    'Leyndell Soldier Greaves',
    "Lionel's Armor",
    "Lionel's Gauntlets",
    "Lionel's Greaves",
    "Lusat's Manchettes",
    "Lusat's Robe",
    "Malenia's Armor",
    "Malenia's Gauntlet",
    "Malenia's Greaves",
    'Malformed Dragon Armor',
    'Malformed Dragon Gauntlets',
    'Malformed Dragon Greaves',
    "Maliketh's Armor",
    "Maliketh's Gauntlets",
    "Maliketh's Greaves",
    'Marais Robe',
    'Marionette Soldier Armor',
    'Mausoleum Gauntlets',
    'Mausoleum Greaves',
    'Mausoleum Knight Gauntlets',
    'Mausoleum Knight Greaves',
    'Messmer Soldier Armor',
    'Messmer Soldier Gauntlets',
    'Messmer Soldier Greaves',
    "Messmer's Armor",
    "Messmer's Gauntlets",
    "Messmer's Greaves",
    'Mushroom Arms',
    'Mushroom Body',
    'Mushroom Legs',
    'Night Maiden Armor',
    "Night's Cavalry Armor",
    "Night's Cavalry Gauntlets",
    "Night's Cavalry Greaves",
    "Noble's Gloves",
    "Noble's Traveling Garb",
    "Noble's Trousers",
    "Nomadic Merchant's Finery",
    "Nomadic Merchant's Trousers",
    'Nox Bracelets',
    'Nox Greaves',
    'Nox Monk Armor',
    'Nox Swordstress Armor',
    'Oathseeker Knight Gauntlets',
    'Oathseeker Knight Greaves',
    "Official's Attire",
    'Old Aristocrat Gown',
    'Old Aristocrat Shoes',
    "Old Sorcerer's Legwraps",
    'Omen Armor',
    'Omen Gauntlets',
    'Omen Greaves',
    'Omenkiller Boots',
    'Omenkiller Long Gloves',
    'Omenkiller Robe',
    'Page Garb',
    'Page Trousers',
    'Perfumer Gloves',
    'Perfumer Robe',
    'Perfumer Sarong',
    "Perfumer's Traveling Garb",
    "Preceptor's Gloves",
    "Preceptor's Long Gown",
    "Preceptor's Trousers",
    'Prisoner Clothing',
    'Prisoner Trousers',
    'Prophet Trousers',
    "Queen's Bracelets",
    "Queen's Leggings",
    "Queen's Robe",
    'Radahn Soldier Gauntlets',
    'Radahn Soldier Greaves',
    "Radahn's Gauntlets",
    "Radahn's Greaves",
    "Radahn's Lion Armor",
    'Raging Wolf Armor',
    'Raging Wolf Gauntlets',
    'Raging Wolf Greaves',
    'Rakshasa Armor',
    'Rakshasa Gauntlets',
    'Rakshasa Greaves',
    "Raptor's Black Feathers",
    'Raya Lucarian Gauntlets',
    'Raya Lucarian Greaves',
    'Raya Lucarian Robe',
    'Redmane Knight Armor',
    'Redmane Knight Gauntlets',
    'Redmane Knight Greaves',
    'Redmane Surcoat',
    "Rellana's Armor",
    "Rellana's Gloves",
    "Rellana's Greaves",
    "Ronin's Armor",
    "Ronin's Gauntlets",
    "Ronin's Greaves",
    'Rotten Duelist Greaves',
    'Rotten Gravekeeper Cloak',
    'Royal Knight Armor',
    'Royal Knight Gauntlets',
    'Royal Knight Greaves',
    'Royal Remains Armor',
    'Royal Remains Gauntlets',
    'Royal Remains Greaves',
    "Ruler's Robe",
    'Sage Robe',
    'Sage Trousers',
    'Sanguine Noble Robe',
    'Sanguine Noble Waistcloth',
    'Scale Armor',
    'Scaled Armor',
    'Scaled Gauntlets',
    'Scaled Greaves',
    'Scarlet Tabard',
    'Shadow Militiaman Armor',
    'Shadow Militiaman Gauntlets',
    'Shadow Militiaman Greaves',
    'Shaman Furs',
    'Shaman Leggings',
    'Snow Witch Robe',
    'Snow Witch Skirt',
    'Soiled Loincloth',
    'Sorcerer Leggings',
    'Sorcerer Manchettes',
    "Spellblade's Gloves",
    "Spellblade's Traveling Attire",
    "Spellblade's Trousers",
    "Thiollier's Garb",
    "Thiollier's Gloves",
    "Thiollier's Trousers",
    "Traveler's Boots",
    "Traveler's Gloves",
    "Traveler's Manchettes",
    "Traveler's Slops",
    'Traveling Maiden Boots',
    'Traveling Maiden Gloves',
    'Traveling Maiden Robe',
    'Tree Sentinel Armor',
    'Tree Sentinel Gauntlets',
    'Tree Sentinel Greaves',
    'Tree-and-Beast Surcoat',
    'Twinned Armor',
    'Twinned Gauntlets',
    'Twinned Greaves',
    'Vagabond Knight Armor',
    'Vagabond Knight Gauntlets',
    'Vagabond Knight Greaves',
    'Verdigris Armor',
    'Verdigris Gauntlets',
    'Verdigris Greaves',
    "Veteran's Armor",
    "Veteran's Gauntlets",
    "Veteran's Greaves",
    'Vulgar Militia Armor',
    'Vulgar Militia Gauntlets',
    'Vulgar Militia Greaves',
    'War Surgeon Gloves',
    'War Surgeon Trousers',
    'Warrior Gauntlets',
    'Warrior Greaves',
    'White Reed Armor',
    'White Reed Gauntlets',
    'White Reed Greaves',
    "Young Lion's Armor",
    "Young Lion's Gauntlets",
    "Young Lion's Greaves",
    'Zamor Armor',
    'Zamor Bracelets',
    'Zamor Legwraps',
})



# =====================================================================================
# relevance_uplift (dlc_only) -- SPEC-relevance-uplift.md, Alaric 2026-06-16.
# Swap worst DLC *material* filler out of the item pool, inject base-game juice 1:1.
# Mirror of dlc_gear_curation (injected <= skippable, count-neutral). The cut PREDICATE
# and the inject builder live in __init__.py (_curate_defer_dlc_filler /
# _uplift_inject_names); these are the data tables they read. S-tier weapons/armor/spells
# are pulled from item_tiers.ITEM_TIERS at runtime, so only the categories item_tiers
# doesn't cover yet are hand-listed here. Names verified against items.py item_table.
# =====================================================================================

# One-off "actually keep this DLC filler" overrides (surfaced by the report).
UPLIFT_KEEP_DLC = frozenset()

# Top base-game spirit ashes -- biggest solo-run difficulty lever.
UPLIFT_SPIRITS_TOP = frozenset({
    "Mimic Tear Ashes",
    "Black Knife Tiche",
    "Lhutel the Headless",
    "Redmane Knight Ogha",
    "Ancient Dragon Knight Kristoff",
    "Greatshield Soldier Ashes",
    "Latenna the Albinauric",
    "Nightmaiden & Swordstress Puppets",
    "Cleanrot Knight Finlay",
    "Dung Eater Puppet",
    "Banished Knight Oleg",
})

# PROVISIONAL S/A talismans (community PvE refs, 2026-06-16). Phase 2: fold ACCESSORY into
# the item_tiers.tsv pipeline like weapons/armor/spells, then retire this hand list.
UPLIFT_TALISMANS_S = frozenset({
    "Erdtree's Favor +2",
    "Radagon's Soreseal",
    "Marika's Soreseal",
    "Shard of Alexander",
    "Godfrey Icon",
    "Radagon Icon",
    "Old Lord's Talisman",
    "Gold Scarab",
    "Millicent's Prosthesis",
    "Ritual Sword Talisman",
    "Graven-Mass Talisman",
    "Dragoncrest Greatshield Talisman",
    "Crimson Amber Medallion +2",
    "Blessed Dew Talisman",
})

# Glovewort bell bearings -- unlock spirit-ash upgrade mats at the merchant so injected
# spirits can scale. Non-progression, so they ride the count-neutral swap.
UPLIFT_GLOVEWORT_BELLS = frozenset({
    "Glovewort Picker's Bell Bearing [1]",
    "Glovewort Picker's Bell Bearing [2]",
    "Glovewort Picker's Bell Bearing [3]",
    "Ghost-Glovewort Picker's Bell Bearing [1]",
    "Ghost-Glovewort Picker's Bell Bearing [2]",
    "Ghost-Glovewort Picker's Bell Bearing [3]",
})

# All base-game remembrances. Progression-classified in items.py; the inject path
# (_create_uplift_item) downgrades them to useful so they stay out of mandatory-
# progression accounting. (DLC remembrances are excluded by the is_dlc filter.)
UPLIFT_REMEMBRANCES = frozenset({
    "Remembrance of the Grafted",
    "Remembrance of the Starscourge",
    "Remembrance of the Omen King",
    "Remembrance of the Blasphemous",
    "Remembrance of the Rot Goddess",
    "Remembrance of the Blood Lord",
    "Remembrance of the Black Blade",
    "Remembrance of Hoarah Loux",
    "Remembrance of the Dragonlord",
    "Remembrance of the Full Moon Queen",
    "Remembrance of the Lichdragon",
    "Remembrance of the Fire Giant",
    "Remembrance of the Regal Ancestor",
    "Elden Remembrance",
    "Remembrance of the Naturalborn",
})

# Permanent character upgrades -- count-capped uniques (extra copies wasted).
UPLIFT_UNIQUE_CAPS = {
    "Memory Stone": 8,
    "Talisman Pouch": 3,
    "Margit's Shackle": 1,   # base goods 2140 -- inject into dlc_only juice pool
    "Mohg's Shackle": 1,     # base goods 2150 -- inject into dlc_only juice pool
}

# Flask economy stackables.
UPLIFT_SEEDS_TEARS = frozenset({
    "Golden Seed",
    "Sacred Tear",
})

# Juicy-rune threshold: any base-game rune consumable >= this many runes (Numen's=12500,
# Lord's=50000, Hero's, Golden [10]+) is eligible as a stackable inject.
UPLIFT_RUNE_MIN_VALUE = 5000

# Weighted distribution for the stackable remainder once all uniques are placed.
UPLIFT_STACKABLE_WEIGHTS = {
    "runes": 60,
    "seeds_tears": 40,
}

# --- NPC questline de-randomization (SPEC-questline-derando.md) --------------------
# UNIQUE quest LINK items that gate only optional locations (never a region or a goal).
# Locking these at vanilla satisfies each chain in normal play and pulls dead-weight
# progression out of the fill. EXEMPT (region/goal-gating; deliberately NOT listed):
#   Drawing-Room Key (Volcano Manor), Haligtree Secret Medallion L/R (Haligtree),
#   Hole-Laden Necklace (Cathedral of Manus Metyr).
# Multi-location consumables (Starlight Shards, Seedbed Curse, Shabriri Grape, and the
# x2 DLC items) are excluded -- a name-keyed cut would also hit their non-quest spots.
QUESTLINE_DERANDO = frozenset({
    # Sellen
    "Sellen's Primal Glintstone", "Sellian Sealbreaker", "Academy Glintstone Key (Thops)",
    # Ranni
    "Carian Inverted Statue", "Miniature Ranni", "Dark Moon Ring", "Fingerslayer Blade",
    # Seluvis / Preceptor Seluvis
    "Seluvis's Potion", "Amber Draught", "Amber Starlight", "Dancer's Castanets",
    # Volcano Manor / Rya
    "Rya's Necklace", "Serpent's Amnion", "Lord of Blood's Favor",
    # Millicent
    "Unalloyed Gold Needle (Broken)", "Unalloyed Gold Needle (Fixed)",
    "Unalloyed Gold Needle (Milicent)", "Valkyrie's Prosthesis",
    # Fia / D / Rogier
    "Weathered Dagger", "Black Knifeprint", "Cursemark of Death",
    # DLC (Hornsent secret rite)
    "Secret Rite Scroll",
    # extras v4 (unplaced-audit 2026-06-19): Law of Regression (refs=0), Chrysalids' Memento
    # (gates only a Roderika Golden Seed -- Seedtree check stays reachable when locked).
    "Law of Regression", "Chrysalids' Memento",
    # extras v3 (unplaced-audit 2026-06-19): Academy Glintstone Crowns (Converted Tower puzzle),
    # the rest of the merchant prayerbooks (refs=0), and Fingerprint Grape (frenzied puzzle).
    "Twinsage Glintstone Crown", "Olivinus Glintstone Crown", "Lazuli Glintstone Crown",
    "Karolos Glintstone Crown", "Witch's Glintstone Crown",
    "Godskin Prayerbook", "Assassin's Prayerbook", "Fire Monks' Prayerbook",
    "Giant's Prayerbook", "Dragon Cult Prayerbook", "Ancient Dragon Prayerbook",
    "Fingerprint Grape",
    # extras v2 (unplaced-audit 2026-06-19): all paintings + scrolls + Margit's Shackle (refs=0)
    "\"Homing Instinct\" Painting", "\"Champion's Song\" Painting", "\"Sorcerer\" Painting",
    "\"Prophecy\" Painting", "\"Flightless Bird\" Painting", "\"Redmane\" Painting",
    "\"Resurrection\" Painting", "\"Incursion\" Painting", "\"The Sacred Tower\" Painting",
    "\"Domain of Dragons\" Painting",
    "Royal House Scroll", "Academy Scroll", "Conspectus Scroll", "Margit's Shackle",
    # extras (unplaced-audit 2026-06-19): unique quest items, optional-gating only
    "Two Fingers' Prayerbook", "Golden Order Principia",
    "Twinned Helm", "Twinned Armor", "Twinned Gauntlets", "Twinned Greaves",
    '"Resurrection" Painting', "Mohg's Shackle",
})

# Good terminal rewards: in 'full' mode their reward LOCATION is also locked at vanilla and
# a shuffled copy is re-injected at the expense of one filler (count-neutral), so the item
# stays obtainable without grinding the quest.
QUESTLINE_REWARD_INJECT = frozenset({
    "Dark Moon Greatsword",          # Ranni
    "Stars of Ruin",                 # Sellen
    "Rotten Winged Sword Insignia",  # Millicent
    "Millicent's Prosthesis",        # Millicent
    "Inseparable Sword",             # Fia / D
    "Magic Scorpion Charm",          # Seluvis
    "Taker's Cameo",                 # Volcano Manor
})
