# -*- coding: utf-8 -*-
"""AUTO-GENERATED PvE tier data for the check-trim pass. Source: item_tiers.tsv
(see elden-ring-tier-list.md and SPEC-check-trim.md). Regenerate from the TSV;
do not hand-edit. item name -> PvE tier letter (S best .. F worst).
"""

ITEM_TIERS = {
    "Academy Glintstone Staff": "A",
    "Adula's Moonblade": "S",
    "Alabaster Lord's Sword": "B",
    "Alberich's Bracers": "B",
    "Alberich's Pointed Hat": "B",
    "Alberich's Robe": "B",
    "Alberich's Trousers": "B",
    "Albinauric Bow": "C",
    "Albinauric Mask": "F",
    "Albinauric Staff": "B",
    "All-Knowing Armor": "B",
    "All-Knowing Gauntlets": "B",
    "All-Knowing Greaves": "B",
    "All-Knowing Helm": "B",
    "Ancient Dragons' Lightning Spear": "S",
    "Ancient Dragons' Lightning Strike": "S",
    "Ancient Meteoric Ore Greatsword": "A",
    "Ansbach's Attire": "C",
    "Ansbach's Boots": "C",
    "Ansbach's Longbow": "C",
    "Ansbach's Manchettes": "C",
    "Antspur Rapier": "A",
    "Anvil Hammer": "A",
    "Arbalest": "B",
    "Aristocrat Boots": "D",
    "Aristocrat Coat": "D",
    "Aristocrat Garb": "D",
    "Aristocrat Garb (Altered)": "D",
    "Aristocrat Hat": "D",
    "Aristocrat Headband": "D",
    "Armor of Night": "B",
    "Armor of Solitude": "A",
    "Ascetic's Ankle Guards": "D",
    "Ascetic's Loincloth": "D",
    "Ascetic's Wrist Guards": "D",
    "Ash of War: Aspects of the Crucible: Wings": "B",
    "Ash of War: Assassin's Gambit": "B",
    "Ash of War: Barbaric Roar": "A",
    "Ash of War: Barrage": "C",
    "Ash of War: Barricade Shield": "C",
    "Ash of War: Beast's Roar": "B",
    "Ash of War: Black Flame Tornado": "A",
    "Ash of War: Blinkbolt": "A",
    "Ash of War: Blood Blade": "C",
    "Ash of War: Blood Tax": "B",
    "Ash of War: Bloodhound's Step": "S",
    "Ash of War: Bloody Slash": "A",
    "Ash of War: Carian Grandeur": "A",
    "Ash of War: Carian Greatsword": "B",
    "Ash of War: Carian Retaliation": "B",
    "Ash of War: Carian Sovereignty": "A",
    "Ash of War: Charge Forth": "C",
    "Ash of War: Chilling Mist": "C",
    "Ash of War: Cragblade": "A",
    "Ash of War: Determination": "S",
    "Ash of War: Divine Beast Frost Stomp": "A",
    "Ash of War: Double Slash": "C",
    "Ash of War: Dryleaf Whirlwind": "B",
    "Ash of War: Earthshaker": "A",
    "Ash of War: Enchanted Shot": "C",
    "Ash of War: Endure": "A",
    "Ash of War: Eruption": "B",
    "Ash of War: Flame Skewer": "C",
    "Ash of War: Flame Spear": "C",
    "Ash of War: Flame of the Redmanes": "S",
    "Ash of War: Flaming Strike": "A",
    "Ash of War: Ghostflame Call": "B",
    "Ash of War: Giant Hunt": "A",
    "Ash of War: Glintstone Pebble": "C",
    "Ash of War: Golden Land": "B",
    "Ash of War: Golden Parry": "B",
    "Ash of War: Golden Slam": "B",
    "Ash of War: Golden Vow": "S",
    "Ash of War: Gravitas": "B",
    "Ash of War: Ground Slam": "C",
    "Ash of War: Hoarah Loux's Earthshaker": "A",
    "Ash of War: Hoarfrost Stomp": "A",
    "Ash of War: Holy Ground": "B",
    "Ash of War: Ice Spear": "C",
    "Ash of War: Impaling Thrust": "C",
    "Ash of War: Kick": "D",
    "Ash of War: Lifesteal Fist": "B",
    "Ash of War: Lightning Ram": "B",
    "Ash of War: Lightning Slash": "A",
    "Ash of War: Lion's Claw": "S",
    "Ash of War: Loretta's Slash": "B",
    "Ash of War: Mighty Shot": "C",
    "Ash of War: No Skill": "F",
    "Ash of War: Parry": "C",
    "Ash of War: Phantom Slash": "A",
    "Ash of War: Piercing Throw": "C",
    "Ash of War: Poison Moth Flight": "B",
    "Ash of War: Poisonous Mist": "D",
    "Ash of War: Prayerful Strike": "B",
    "Ash of War: Prelate's Charge": "A",
    "Ash of War: Quickstep": "A",
    "Ash of War: Raging Beast": "B",
    "Ash of War: Rain of Arrows": "B",
    "Ash of War: Raptor of the Mists": "A",
    "Ash of War: Repeating Thrust": "B",
    "Ash of War: Rolling Sparks": "B",
    "Ash of War: Royal Knight's Resolve": "S",
    "Ash of War: Sacred Blade": "B",
    "Ash of War: Sacred Order": "B",
    "Ash of War: Sacred Ring of Light": "B",
    "Ash of War: Savage Lion's Claw": "S",
    "Ash of War: Scattershot Throw": "C",
    "Ash of War: Seppuku": "S",
    "Ash of War: Shared Order": "C",
    "Ash of War: Shield Bash": "C",
    "Ash of War: Shield Crash": "B",
    "Ash of War: Shriek of Sorrow": "B",
    "Ash of War: Sky Shot": "C",
    "Ash of War: Spectral Lance": "B",
    "Ash of War: Spinning Slash": "B",
    "Ash of War: Spinning Weapon": "B",
    "Ash of War: Square Off": "A",
    "Ash of War: Stamp (Sweep)": "B",
    "Ash of War: Stamp (Upward Cut)": "A",
    "Ash of War: Storm Assault": "B",
    "Ash of War: Storm Blade": "A",
    "Ash of War: Storm Stomp": "B",
    "Ash of War: Storm Wall": "C",
    "Ash of War: Stormcaller": "B",
    "Ash of War: Swift Slash": "B",
    "Ash of War: Sword Dance": "B",
    "Ash of War: The Poison Flower Blooms Twice": "A",
    "Ash of War: Thops's Barrier": "D",
    "Ash of War: Through and Through": "B",
    "Ash of War: Thunderbolt": "B",
    "Ash of War: Troll's Roar": "B",
    "Ash of War: Unsheathe": "A",
    "Ash of War: Vacuum Slice": "B",
    "Ash of War: Vow of the Indomitable": "B",
    "Ash of War: Wall of Sparks": "C",
    "Ash of War: War Cry": "A",
    "Ash of War: Waves of Darkness": "S",
    "Ash of War: White Shadow's Lure": "C",
    "Ash of War: Wild Strikes": "B",
    "Ash of War: Wing Stance": "A",
    "Aspects of the Crucible: Tail": "A",
    "Astrologer Gloves": "B",
    "Astrologer Hood": "B",
    "Astrologer Robe": "B",
    "Astrologer Trousers": "B",
    "Astrologer's Staff": "B",
    "Axe of Godfrey": "A",
    "Axe of Godrick": "A",
    "Azur's Glintstone Crown": "B",
    "Azur's Glintstone Robe": "B",
    "Azur's Glintstone Staff": "S",
    "Azur's Manchettes": "B",
    "Backhand Blade": "S",
    "Bandit Boots": "C",
    "Bandit Garb": "C",
    "Bandit Manchettes": "C",
    "Bandit Mask": "C",
    "Bandit's Curved Sword": "B",
    "Banished Knight Armor": "S",
    "Banished Knight Armor (Altered)": "S",
    "Banished Knight Gauntlets": "S",
    "Banished Knight Greaves": "S",
    "Banished Knight Helm": "S",
    "Banished Knight Helm (Altered)": "S",
    "Banished Knight's Greatsword": "A",
    "Banished Knight's Halberd": "B",
    "Barbed Staff-Spear": "B",
    "Bastard Sword": "A",
    "Bastard's Stars": "A",
    "Battle Axe": "B",
    "Battle Hammer": "B",
    "Battlemage Legwraps": "B",
    "Battlemage Manchettes": "B",
    "Battlemage Robe": "B",
    "Bayle's Tyranny": "A",
    "Beast Champion Armor (Altered)": "S",
    "Beast Champion Gauntlets": "S",
    "Beast Champion Greaves": "S",
    "Beast Champion Helm": "S",
    "Beast Claw": "A",
    "Beast-Repellent Torch": "D",
    "Beastclaw Greathammer": "A",
    "Beastman's Cleaver": "B",
    "Beastman's Curved Sword": "A",
    "Black Blade": "A",
    "Black Bow": "A",
    "Black Flame": "A",
    "Black Knife": "A",
    "Black Knife Armor": "B",
    "Black Knife Gauntlets": "B",
    "Black Knife Greaves": "B",
    "Black Knife Hood": "B",
    "Black Knight Armor": "A",
    "Black Knight Gauntlets": "A",
    "Black Knight Greaves": "A",
    "Black Knight Helm": "A",
    "Black Steel Greathammer": "A",
    "Black Steel Greatshield": "B",
    "Black Steel Twinblade": "A",
    "Blackflame Monk Armor": "B",
    "Blackflame Monk Gauntlets": "B",
    "Blackflame Monk Greaves": "B",
    "Blackflame Monk Hood": "B",
    "Blade of Calling": "B",
    "Blades of Stone": "A",
    "Blaidd's Armor": "A",
    "Blaidd's Gauntlets": "A",
    "Blaidd's Greaves": "A",
    "Blasphemous Blade": "S",
    "Bloodfiend's Arm": "S",
    "Bloodfiend's Fork": "B",
    "Bloodfiend's Sacred Spear": "F",
    "Bloodflame Talons": "A",
    "Bloodhound Claws": "A",
    "Bloodhound Knight Armor": "C",
    "Bloodhound Knight Gauntlets": "C",
    "Bloodhound Knight Greaves": "C",
    "Bloodhound Knight Helm": "C",
    "Bloodhound's Fang": "S",
    "Bloodsoaked Manchettes": "F",
    "Bloodsoaked Mask": "F",
    "Bloodsoaked Tabard": "F",
    "Bloodstained Dagger": "C",
    "Bloody Helice": "A",
    "Blue Cloth Cowl": "B",
    "Blue Cloth Vest": "B",
    "Blue Silver Bracelets": "C",
    "Blue Silver Mail Armor": "C",
    "Blue Silver Mail Hood": "C",
    "Blue Silver Mail Skirt": "C",
    "Bolt of Gransax": "A",
    "Bone Bow": "B",
    "Bonny Butchering Knife": "C",
    "Borealis's Mist": "A",
    "Braided Arm Wraps": "D",
    "Braided Cord Robe": "D",
    "Briar Armor": "A",
    "Briar Gauntlets": "A",
    "Briar Greaves": "A",
    "Briar Helm": "A",
    "Brick Hammer": "B",
    "Broadsword": "B",
    "Bull-Goat Armor": "S",
    "Bull-Goat Gauntlets": "S",
    "Bull-Goat Greaves": "S",
    "Bull-Goat Helm": "S",
    "Caestus": "B",
    "Cane Sword": "B",
    "Carian Glintblade Staff": "B",
    "Carian Glintstone Staff": "A",
    "Carian Greatsword": "A",
    "Carian Knight Armor": "B",
    "Carian Knight Gauntlets": "B",
    "Carian Knight Greaves": "B",
    "Carian Knight Helm": "B",
    "Carian Knight's Sword": "B",
    "Carian Piercer": "A",
    "Carian Regal Scepter": "S",
    "Carian Slicer": "A",
    "Carian Sorcery Sword": "B",
    "Carian Thrusting Shield": "S",
    "Caterpillar Mask": "D",
    "Celebrant's Cleaver": "C",
    "Celebrant's Rib-Rake": "C",
    "Celebrant's Sickle": "C",
    "Celebrant's Skull": "C",
    "Chain Armor": "D",
    "Chain Coif": "D",
    "Chain Leggings": "D",
    "Chain-Draped Tabard": "D",
    "Chainlink Flail": "B",
    "Champion Bracers": "D",
    "Champion Gaiters": "D",
    "Champion Headband": "D",
    "Champion Pauldron": "D",
    "Chilling Perfume Bottle": "C",
    "Cinquedea": "B",
    "Cipher Pata": "A",
    "Clawmark Seal": "A",
    "Claws of Night": "S",
    "Clayman's Harpoon": "B",
    "Claymore": "A",
    "Cleanrot Armor": "S",
    "Cleanrot Gauntlets": "S",
    "Cleanrot Greaves": "S",
    "Cleanrot Helm": "S",
    "Cleanrot Knight's Sword": "B",
    "Cleanrot Spear": "B",
    "Clinging Bone": "B",
    "Cloth Garb": "D",
    "Cloth Trousers": "D",
    "Club": "B",
    "Coded Sword": "A",
    "Collapsing Stars": "A",
    "Comet": "S",
    "Comet Azur": "S",
    "Commander's Standard": "A",
    "Common Soldier Cloth Armor": "C",
    "Common Soldier Gauntlets": "C",
    "Common Soldier Greaves": "C",
    "Common Soldier Helm": "C",
    "Commoner's Garb": "D",
    "Commoner's Headband": "D",
    "Commoner's Headband (Altered)": "D",
    "Commoner's Shoes": "D",
    "Commoner's Simple Garb": "D",
    "Composite Bow": "B",
    "Confessor Armor": "A",
    "Confessor Boots": "A",
    "Confessor Gloves": "A",
    "Confessor Hood": "A",
    "Consort's Mask": "C",
    "Consort's Robe": "C",
    "Consort's Trousers": "C",
    "Cranial Vessel Candlestand": "C",
    "Crepus's Black-Key Crossbow": "B",
    "Crescent Moon Axe": "A",
    "Cross-Naginata": "A",
    "Crucible Axe Armor": "S",
    "Crucible Axe Helm": "S",
    "Crucible Gauntlets": "S",
    "Crucible Greaves": "S",
    "Crucible Hammer-Helm": "S",
    "Crucible Tree Armor": "S",
    "Crucible Tree Helm": "S",
    "Crystal Knife": "B",
    "Crystal Spear": "B",
    "Crystal Staff": "B",
    "Crystal Sword": "B",
    "Cuckoo Knight Armor": "A",
    "Cuckoo Knight Gauntlets": "A",
    "Cuckoo Knight Greaves": "A",
    "Cuckoo Knight Helm": "A",
    "Curseblade Mask": "C",
    "Curseblade's Cirque": "A",
    "Curved Club": "C",
    "Curved Great Club": "B",
    "Dagger": "C",
    "Dancer's Bracer": "C",
    "Dancer's Dress": "C",
    "Dancer's Hood": "C",
    "Dancer's Trousers": "C",
    "Dancing Blade of Ranah": "S",
    "Dane's Footwork": "B",
    "Dark Moon Greatsword": "S",
    "Deadly Poison Perfume Bottle": "C",
    "Death Knight Armor": "A",
    "Death Knight Gauntlets": "A",
    "Death Knight Greaves": "A",
    "Death Knight Helm": "A",
    "Death Knight's Longhaft Axe": "A",
    "Death Knight's Twin Axes": "B",
    "Death Ritual Spear": "B",
    "Death's Poker": "A",
    "Demi-Human Queen's Staff": "C",
    "Depraved Perfumer Gloves": "B",
    "Depraved Perfumer Headscarf": "B",
    "Depraved Perfumer Robe": "B",
    "Depraved Perfumer Trousers": "B",
    "Devonia's Hammer": "D",
    "Devourer's Scepter": "A",
    "Digger's Staff": "B",
    "Discus of Light": "A",
    "Dismounter": "A",
    "Divine Beast Head": "B",
    "Divine Beast Helm": "B",
    "Divine Beast Warrior Armor": "B",
    "Divine Bird Helm": "B",
    "Divine Bird Warrior Armor": "B",
    "Divine Bird Warrior Gauntlets": "B",
    "Divine Bird Warrior Greaves": "B",
    "Dragon Communion Seal": "S",
    "Dragon Greatclaw": "B",
    "Dragon Halberd": "A",
    "Dragon King's Cragblade": "A",
    "Dragon-Hunter's Great Katana": "S",
    "Dragonbolt Blessing": "A",
    "Dragonbolt of Florissax": "A",
    "Dragonscale Blade": "A",
    "Drake Knight Armor": "C",
    "Drake Knight Gauntlets": "C",
    "Drake Knight Greaves": "C",
    "Drake Knight Helm": "C",
    "Dryleaf Arm Wraps": "D",
    "Dryleaf Arts": "B",
    "Dryleaf Cuissardes": "D",
    "Dryleaf Robe": "D",
    "Dryleaf Seal": "A",
    "Dueling Shield": "A",
    "Duelist Greataxe": "A",
    "Duelist Greaves": "C",
    "Duelist Helm": "C",
    "Eccentric's Armor": "C",
    "Eccentric's Breeches": "C",
    "Eccentric's Hood": "C",
    "Eccentric's Manchettes": "C",
    "Eclipse Shotel": "A",
    "Ekzykes's Decay": "A",
    "Elden Lord Armor": "C",
    "Elden Lord Bracers": "C",
    "Elden Lord Crown": "C",
    "Elden Lord Greaves": "C",
    "Eleonora's Poleblade": "S",
    "Envoy's Greathorn": "B",
    "Envoy's Horn": "D",
    "Envoy's Long Horn": "A",
    "Erdsteel Dagger": "B",
    "Erdtree Bow": "B",
    "Erdtree Greatbow": "A",
    "Erdtree Seal": "S",
    "Errant Sorcerer Boots": "B",
    "Errant Sorcerer Manchettes": "B",
    "Errant Sorcerer Robe (Altered)": "B",
    "Estoc": "A",
    "Euporia": "A",
    "Executioner's Greataxe": "A",
    "Exile Armor": "C",
    "Exile Gauntlets": "C",
    "Exile Greaves": "C",
    "Exile Hood": "C",
    "Falchion": "B",
    "Fallingstar Beast Jaw": "S",
    "Falx": "A",
    "Family Heads": "B",
    "Fang Helm": "D",
    "Festive Garb": "F",
    "Festive Garb (Altered)": "F",
    "Festive Hood": "F",
    "Fia's Hood": "F",
    "Fia's Robe": "F",
    "Finger Maiden Fillet": "C",
    "Finger Maiden Robe": "C",
    "Finger Maiden Shoes": "C",
    "Finger Seal": "A",
    "Fingerprint Armor": "B",
    "Fingerprint Gauntlets": "B",
    "Fingerprint Greaves": "B",
    "Fingerprint Helm": "B",
    "Fire Knight Armor": "A",
    "Fire Knight Gauntlets": "A",
    "Fire Knight Greaves": "A",
    "Fire Knight Helm": "A",
    "Fire Knight's Greatsword": "S",
    "Fire Knight's Seal": "B",
    "Fire Knight's Shortsword": "C",
    "Fire Monk Armor": "B",
    "Fire Monk Gauntlets": "B",
    "Fire Monk Greaves": "B",
    "Fire Monk Hood": "B",
    "Fire Prelate Armor": "S",
    "Fire Prelate Armor (Altered)": "S",
    "Fire Prelate Gauntlets": "S",
    "Fire Prelate Greaves": "S",
    "Fire Prelate Helm": "S",
    "Fire Serpent": "A",
    "Firespark Perfume Bottle": "B",
    "Flail": "B",
    "Flamberge": "A",
    "Flame Sling": "A",
    "Flame of the Fell God": "A",
    "Flame, Cleanse Me": "A",
    "Flame, Grant Me Strength": "S",
    "Flowerstone Gavel": "A",
    "Flowing Curved Sword": "A",
    "Foot Soldier Cap": "A",
    "Foot Soldier Gauntlets": "A",
    "Foot Soldier Greaves": "A",
    "Foot Soldier Helm": "A",
    "Foot Soldier Helmet": "A",
    "Foot Soldier Tabard": "A",
    "Forked Greatsword": "B",
    "Forked Hatchet": "C",
    "Forked-Tongue Hatchet": "F",
    "Fortissax's Lightning Spear": "S",
    "Founding Rain of Stars": "A",
    "Frenzied Flame Seal": "A",
    "Frenzyflame Perfume Bottle": "B",
    "Freyja's Armor": "B",
    "Freyja's Gauntlets": "B",
    "Freyja's Greatsword": "B",
    "Freyja's Greaves": "B",
    "Freyja's Helm": "B",
    "Frozen Needle": "A",
    "Full Moon Crossbow": "B",
    "Fur Leggings": "D",
    "Fur Raiment": "D",
    "Furious Blade of Ansbach": "A",
    "Gaius's Armor": "B",
    "Gaius's Gauntlets": "B",
    "Gaius's Greaves": "B",
    "Gaius's Helm": "B",
    "Gargoyle's Black Axe": "A",
    "Gargoyle's Black Blades": "A",
    "Gargoyle's Black Halberd": "B",
    "Gargoyle's Blackblade": "A",
    "Gargoyle's Great Axe": "B",
    "Gargoyle's Greatsword": "A",
    "Gargoyle's Halberd": "B",
    "Gargoyle's Twinblade": "A",
    "Gauntlets of Night": "B",
    "Gauntlets of Solitude": "A",
    "Gazing Finger": "A",
    "Gelmir Glintstone Staff": "A",
    "Gelmir Knight Armor": "A",
    "Gelmir Knight Gauntlets": "A",
    "Gelmir Knight Greaves": "A",
    "Gelmir Knight Helm": "A",
    "Ghiza's Wheel": "S",
    "Ghostflame Torch": "D",
    "Giant's Red Braid": "A",
    "Giant's Seal": "A",
    "Giant-Crusher": "S",
    "Giantsflame Take Thee": "A",
    "Glaive": "B",
    "Glintblade Trio": "A",
    "Glintstone Cometshard": "A",
    "Glintstone Kris": "B",
    "Glintstone Nails": "A",
    "Glintstone Staff": "B",
    "Gloried Attire": "D",
    "Godrick Knight Armor": "A",
    "Godrick Knight Gauntlets": "A",
    "Godrick Knight Greaves": "A",
    "Godrick Knight Helm": "A",
    "Godrick Soldier Gauntlets": "B",
    "Godrick Soldier Greaves": "B",
    "Godrick Soldier Helm": "B",
    "Godskin Apostle Bracelets": "B",
    "Godskin Apostle Hood": "B",
    "Godskin Apostle Robe": "B",
    "Godskin Apostle Trousers": "B",
    "Godskin Noble Bracelets": "A",
    "Godskin Noble Hood": "A",
    "Godskin Noble Robe": "A",
    "Godskin Noble Trousers": "A",
    "Godskin Peeler": "A",
    "Godskin Stitcher": "A",
    "Godslayer's Greatsword": "S",
    "Godslayer's Seal": "A",
    "Gold Bracelets": "C",
    "Gold Waistwrap": "C",
    "Golden Epitaph": "B",
    "Golden Halberd": "B",
    "Golden Lion Shield": "C",
    "Golden Order Greatsword": "S",
    "Golden Order Seal": "S",
    "Golden Vow (Incantation)": "S",
    "Goldmask's Rags": "C",
    "Golem Fist": "C",
    "Golem Greatbow": "C",
    "Golem's Halberd": "A",
    "Grafted Blade Greatsword": "A",
    "Grafted Dragon": "A",
    "Grave Scythe": "B",
    "Gravebird Anklets": "C",
    "Gravebird Armor": "C",
    "Gravebird Bracelets": "C",
    "Gravebird Helm": "C",
    "Gravebird's Blackquill Armor": "C",
    "Gravel Stone Seal": "A",
    "Gravitational Missile": "A",
    "Great Club": "B",
    "Great Katana": "A",
    "Great Knife": "B",
    "Great Mace": "B",
    "Great Omenkiller Cleaver": "B",
    "Great Stars": "A",
    "Great Épée": "A",
    "Greataxe": "A",
    "Greatblade Phalanx": "A",
    "Greatbow": "B",
    "Greathorn Hammer": "B",
    "Greatsword": "A",
    "Greatsword of Damnation": "A",
    "Greatsword of Radahn (Light)": "C",
    "Greatsword of Radahn (Lord)": "A",
    "Greatsword of Solitude": "S",
    "Greaves of Night": "B",
    "Greaves of Solitude": "A",
    "Grossmesser": "B",
    "Guardian Bracers": "B",
    "Guardian Garb": "B",
    "Guardian Garb (Full Bloom)": "B",
    "Guardian Greaves": "B",
    "Guardian Mask": "B",
    "Guardian's Swordspear": "A",
    "Guilty Hood": "D",
    "Halberd": "B",
    "Haligtree Crest Surcoat": "B",
    "Haligtree Gauntlets": "B",
    "Haligtree Greaves": "B",
    "Haligtree Helm": "B",
    "Haligtree Knight Armor": "B",
    "Haligtree Knight Gauntlets": "B",
    "Haligtree Knight Greaves": "B",
    "Haligtree Knight Helm": "B",
    "Halo Scythe": "A",
    "Hammer": "B",
    "Hand Axe": "B",
    "Hand Ballista": "B",
    "Hand of Malenia": "S",
    "Harp Bow": "B",
    "Heavy Crossbow": "B",
    "Helm of Night": "B",
    "Helm of Solitude": "A",
    "Helphen's Steeple": "A",
    "High Page Clothes": "D",
    "High Page Hood": "D",
    "High Priest Gloves": "D",
    "High Priest Hat": "D",
    "High Priest Robe": "D",
    "High Priest Undergarments": "D",
    "Highland Attire": "D",
    "Highland Axe": "B",
    "Highwayman Cloth Armor": "C",
    "Highwayman Gauntlets": "C",
    "Highwayman Hood": "C",
    "Hookclaws": "B",
    "Horn Bow": "B",
    "Horned Warrior Armor": "B",
    "Horned Warrior Gauntlets": "B",
    "Horned Warrior Greaves": "B",
    "Horned Warrior Helm": "B",
    "Horned Warrior's Greatsword": "B",
    "Horned Warrior's Sword": "B",
    "Hoslow's Armor": "B",
    "Hoslow's Gauntlets": "B",
    "Hoslow's Greaves": "B",
    "Hoslow's Helm": "B",
    "Hoslow's Petal Whip": "A",
    "Howl of Shabriri": "A",
    "Icerind Hatchet": "B",
    "Igon's Armor": "C",
    "Igon's Gauntlets": "C",
    "Igon's Greatbow": "B",
    "Igon's Harpoon": "C",
    "Igon's Helm": "C",
    "Igon's Loincloth": "C",
    "Imp Head (Cat)": "F",
    "Imp Head (Corpse)": "F",
    "Imp Head (Elder)": "F",
    "Imp Head (Fanged)": "F",
    "Imp Head (Lion)": "F",
    "Imp Head (Long-Tongued)": "F",
    "Imp Head (Wolf)": "F",
    "Impenetrable Thorns": "A",
    "Inquisitor's Girandole": "B",
    "Inseparable Sword": "A",
    "Iron Ball": "A",
    "Iron Cleaver": "C",
    "Iron Gauntlets": "D",
    "Iron Greatsword": "B",
    "Iron Helmet": "D",
    "Iron Kasa": "D",
    "Iron Rivet Armor": "D",
    "Iron Rivet Gauntlets": "D",
    "Iron Rivet Greaves": "D",
    "Iron Spear": "B",
    "Ivory Sickle": "C",
    "Jar Cannon": "B",
    "Jawbone Axe": "B",
    "Juvenile Scholar Cap": "F",
    "Juvenile Scholar Robe": "F",
    "Kaiden Armor": "D",
    "Kaiden Gauntlets": "D",
    "Kaiden Helm": "D",
    "Kaiden Trousers": "D",
    "Katar": "B",
    "Knight Armor": "A",
    "Knight Gauntlets": "A",
    "Knight Greaves": "A",
    "Knight Helm": "A",
    "Knight's Greatsword": "B",
    "Knight's Lightning Spear": "S",
    "Lamenting Visage": "C",
    "Lance": "B",
    "Land of Reeds Armor": "A",
    "Land of Reeds Gauntlets": "A",
    "Land of Reeds Greaves": "A",
    "Land of Reeds Helm": "A",
    "Lansseax's Glaive": "S",
    "Large Club": "B",
    "Lazuli Glintstone Crown": "B",
    "Lazuli Glintstone Sword": "B",
    "Lazuli Robe": "C",
    "Leather Arm Wraps": "B",
    "Leather Armor": "B",
    "Leather Boots": "B",
    "Leather Crown": "B",
    "Leather Gloves": "B",
    "Leather Headband": "B",
    "Leather Leg Wraps": "B",
    "Leather Trousers": "B",
    "Leather-Draped Tabard": "B",
    "Leda's Armor": "B",
    "Leda's Sword": "A",
    "Leyndell Knight Armor": "A",
    "Leyndell Knight Gauntlets": "A",
    "Leyndell Knight Greaves": "A",
    "Leyndell Knight Helm": "A",
    "Leyndell Soldier Gauntlets": "B",
    "Leyndell Soldier Greaves": "B",
    "Leyndell Soldier Helm": "B",
    "Light Crossbow": "B",
    "Lightning Perfume Bottle": "B",
    "Lightning Spear": "A",
    "Lion Greatbow": "A",
    "Lionel's Armor": "S",
    "Lionel's Gauntlets": "S",
    "Lionel's Greaves": "S",
    "Lionel's Helm": "S",
    "Lizard Greatsword": "A",
    "Longbow": "B",
    "Longhaft Axe": "B",
    "Longsword": "B",
    "Lord of Blood's Robe": "C",
    "Lordsworn's Greatsword": "B",
    "Lordsworn's Straight Sword": "B",
    "Loretta's Greatbow": "A",
    "Loretta's War Sickle": "A",
    "Lucerne": "B",
    "Lusat's Glintstone Crown": "B",
    "Lusat's Glintstone Staff": "S",
    "Lusat's Manchettes": "B",
    "Lusat's Robe": "B",
    "Mace": "B",
    "Madding Hand": "C",
    "Magma Blade": "B",
    "Magma Whip Candlestick": "B",
    "Magma Wyrm's Scalesword": "A",
    "Main-gauche": "D",
    "Malenia's Armor": "D",
    "Malenia's Gauntlet": "D",
    "Malenia's Greaves": "D",
    "Malenia's Winged Helm": "D",
    "Malformed Dragon Armor": "S",
    "Malformed Dragon Gauntlets": "S",
    "Malformed Dragon Greaves": "S",
    "Malformed Dragon Helm": "S",
    "Maliketh's Armor": "A",
    "Maliketh's Black Blade": "S",
    "Maliketh's Gauntlets": "A",
    "Maliketh's Greaves": "A",
    "Maliketh's Helm": "A",
    "Mantis Blade": "A",
    "Marais Executioner's Sword": "S",
    "Marais Mask": "F",
    "Marais Robe": "F",
    "Marika's Hammer": "A",
    "Marionette Soldier Armor": "F",
    "Marionette Soldier Birdhelm": "F",
    "Marionette Soldier Helm": "F",
    "Maternal Staff": "B",
    "Mausoleum Gauntlets": "C",
    "Mausoleum Greaves": "C",
    "Mausoleum Knight Armor": "C",
    "Mausoleum Knight Gauntlets": "C",
    "Mausoleum Knight Greaves": "C",
    "Mausoleum Surcoat": "C",
    "Messmer Soldier Armor": "C",
    "Messmer Soldier Gauntlets": "C",
    "Messmer Soldier Greaves": "C",
    "Messmer Soldier Helm": "C",
    "Messmer Soldier Shield": "D",
    "Messmer Soldier's Axe": "A",
    "Messmer Soldier's Spear": "A",
    "Messmer's Armor": "A",
    "Messmer's Gauntlets": "A",
    "Messmer's Greaves": "A",
    "Messmer's Helm": "A",
    "Messmer's Orb": "A",
    "Meteoric Ore Blade": "A",
    "Meteorite": "A",
    "Meteorite Staff": "B",
    "Meteorite of Astel": "A",
    "Midra's Flame of Frenzy": "A",
    "Milady": "S",
    "Miquellan Knight's Sword": "B",
    "Misbegotten Shortbow": "C",
    "Miséricorde": "C",
    "Mohgwyn's Sacred Spear": "S",
    "Monk's Flameblade": "A",
    "Monk's Flamemace": "C",
    "Moonrithyll's Knight Sword": "B",
    "Moonveil": "S",
    "Morgott's Cursed Sword": "A",
    "Morning Star": "B",
    "Multilayered Ring of Light": "A",
    "Mushroom Arms": "B",
    "Mushroom Body": "B",
    "Mushroom Crown": "B",
    "Mushroom Head": "B",
    "Mushroom Legs": "B",
    "Nagakiba": "S",
    "Nanaya's Torch": "D",
    "Night Comet": "S",
    "Night Maiden Armor": "A",
    "Night Maiden Twin Crown": "A",
    "Night's Cavalry Armor": "A",
    "Night's Cavalry Gauntlets": "A",
    "Night's Cavalry Greaves": "A",
    "Night's Cavalry Helm": "A",
    "Nightrider Flail": "A",
    "Nightrider Glaive": "A",
    "Noble's Estoc": "B",
    "Noble's Gloves": "B",
    "Noble's Slender Sword": "B",
    "Noble's Traveling Garb": "B",
    "Noble's Trousers": "B",
    "Nomadic Merchant's Chapeau": "D",
    "Nomadic Merchant's Finery": "D",
    "Nomadic Merchant's Trousers": "D",
    "Nox Flowing Hammer": "C",
    "Nox Flowing Sword": "B",
    "Nox Monk Armor": "B",
    "Nox Monk Hood": "B",
    "Nox Swordstress Armor": "A",
    "Nox Swordstress Crown": "A",
    "Oathseeker Knight Armor": "B",
    "Oathseeker Knight Gauntlets": "B",
    "Oathseeker Knight Greaves": "B",
    "Oathseeker Knight Helm": "B",
    "Obsidian Lamina": "B",
    "Old Aristocrat Cowl": "D",
    "Old Aristocrat Gown": "D",
    "Old Aristocrat Shoes": "D",
    "Olivinus Glintstone Crown": "B",
    "Omen Armor": "S",
    "Omen Cleaver": "B",
    "Omen Gauntlets": "S",
    "Omen Greaves": "S",
    "Omen Helm": "S",
    "Omenkiller Boots": "B",
    "Omenkiller Long Gloves": "B",
    "Omenkiller Robe": "B",
    "Omensmirk Mask": "S",
    "Onyx Lord's Greatsword": "B",
    "Ordovis's Greatsword": "A",
    "Ornamental Straight Sword": "C",
    "Page Garb": "C",
    "Page Hood": "C",
    "Page Trousers": "C",
    "Parrying Dagger": "C",
    "Partisan": "B",
    "Pata": "S",
    "Pelt of Ralva": "B",
    "Perfumer Gloves": "B",
    "Perfumer Hood": "B",
    "Perfumer Robe": "B",
    "Perfumer Sarong": "B",
    "Perfumer's Traveling Garb": "B",
    "Pest Threads": "S",
    "Pest's Glaive": "A",
    "Pest-Thread Spears": "S",
    "Pickaxe": "C",
    "Pike": "B",
    "Poisoned Hand": "A",
    "Poleblade of the Bud": "B",
    "Preceptor's Big Hat": "A",
    "Preceptor's Gloves": "A",
    "Preceptor's Long Gown": "A",
    "Preceptor's Trousers": "A",
    "Prelate's Inferno Crozier": "A",
    "Prince of Death's Staff": "A",
    "Prisoner Clothing": "C",
    "Prisoner Iron Mask": "C",
    "Prisoner Trousers": "C",
    "Prophet Blindfold": "C",
    "Prophet Robe": "C",
    "Prophet Trousers": "C",
    "Pulley Bow": "A",
    "Pulley Crossbow": "B",
    "Putrescence Cleaver": "A",
    "Queelign's Greatsword": "B",
    "Queen's Bracelets": "C",
    "Queen's Crescent Crown": "C",
    "Queen's Leggings": "C",
    "Queen's Robe": "C",
    "Rabbath's Cannon": "B",
    "Radahn Soldier Gauntlets": "B",
    "Radahn Soldier Greaves": "B",
    "Radahn Soldier Helm": "B",
    "Radahn's Gauntlets": "S",
    "Radahn's Greaves": "S",
    "Radahn's Lion Armor": "S",
    "Radahn's Redmane Helm": "S",
    "Radiant Gold Mask": "C",
    "Raging Wolf Armor": "C",
    "Raging Wolf Gauntlets": "C",
    "Raging Wolf Greaves": "C",
    "Raging Wolf Helm": "C",
    "Rakshasa Armor": "A",
    "Rakshasa Gauntlets": "A",
    "Rakshasa Greaves": "A",
    "Rakshasa Helm": "A",
    "Rakshasa's Great Katana": "S",
    "Ranni's Dark Moon": "S",
    "Rapier": "A",
    "Raptor Talons": "B",
    "Raptor's Black Feathers": "B",
    "Raya Lucarian Gauntlets": "B",
    "Raya Lucarian Greaves": "B",
    "Raya Lucarian Helm": "B",
    "Raya Lucarian Robe": "B",
    "Red Bear's Claw": "A",
    "Red Branch Shortbow": "C",
    "Redmane Knight Armor": "A",
    "Redmane Knight Gauntlets": "A",
    "Redmane Knight Greaves": "A",
    "Redmane Knight Helm": "A",
    "Reduvia": "A",
    "Regalia of Eochaid": "B",
    "Rellana's Armor": "B",
    "Rellana's Gloves": "B",
    "Rellana's Greaves": "B",
    "Rellana's Helm": "B",
    "Rellana's Twin Blades": "A",
    "Rellana's Twin Moons": "S",
    "Repeating Crossbow": "F",
    "Ringed Finger": "C",
    "Rings of Spectral Light": "A",
    "Ripple Blade": "C",
    "Ripple Crescent Halberd": "B",
    "Rivers of Blood": "S",
    "Rock Sling": "S",
    "Rogier's Rapier": "B",
    "Ronin's Armor": "S",
    "Ronin's Gauntlets": "S",
    "Ronin's Greaves": "S",
    "Rosus' Axe": "B",
    "Rotten Battle Hammer": "D",
    "Rotten Breath": "S",
    "Rotten Crystal Spear": "B",
    "Rotten Crystal Staff": "B",
    "Rotten Crystal Sword": "B",
    "Rotten Duelist Greaves": "B",
    "Rotten Duelist Helm": "B",
    "Rotten Gravekeeper Cloak": "B",
    "Rotten Greataxe": "B",
    "Rotten Staff": "C",
    "Royal Greatsword": "A",
    "Royal Knight Armor": "A",
    "Royal Knight Gauntlets": "A",
    "Royal Knight Greaves": "A",
    "Royal Knight Helm": "A",
    "Royal Remains Armor": "C",
    "Royal Remains Gauntlets": "C",
    "Royal Remains Greaves": "C",
    "Royal Remains Helm": "C",
    "Ruins Greatsword": "A",
    "Ruler's Mask": "D",
    "Ruler's Robe": "D",
    "Rusted Anchor": "A",
    "Sacred Butchering Knife": "B",
    "Sacred Relic Sword": "S",
    "Sacrificial Axe": "B",
    "Sage Hood": "D",
    "Sage Robe": "D",
    "Sage Trousers": "D",
    "Sanguine Noble Hood": "C",
    "Sanguine Noble Robe": "C",
    "Sanguine Noble Waistcloth": "C",
    "Scale Armor": "D",
    "Scaled Armor": "S",
    "Scaled Gauntlets": "S",
    "Scaled Greaves": "S",
    "Scaled Helm": "S",
    "Scarlet Aeonia": "A",
    "Scavenger's Curved Sword": "A",
    "Scepter of the All-Knowing": "D",
    "Scimitar": "B",
    "Scorpion's Stinger": "B",
    "Scythe": "B",
    "Sentry's Torch": "D",
    "Serpent Bow": "A",
    "Serpent Crest Shield": "D",
    "Serpent Flail": "B",
    "Serpent-God's Curved Sword": "A",
    "Serpent-Hunter": "A",
    "Serpentbone Blade": "A",
    "Shadow Militiaman Armor": "C",
    "Shadow Militiaman Gauntlets": "C",
    "Shadow Militiaman Greaves": "C",
    "Shadow Militiaman Helm": "C",
    "Shadow Sunflower Blossom": "A",
    "Shaman Furs": "D",
    "Shaman Leggings": "D",
    "Shamshir": "B",
    "Shield of Night": "C",
    "Short Spear": "C",
    "Short Sword": "B",
    "Shortbow": "B",
    "Shotel": "B",
    "Siluria's Tree": "A",
    "Smithscript Axe": "B",
    "Smithscript Cirque": "A",
    "Smithscript Dagger": "C",
    "Smithscript Greathammer": "B",
    "Smithscript Shield": "A",
    "Smithscript Spear": "C",
    "Snow Witch Hat": "C",
    "Snow Witch Robe": "C",
    "Snow Witch Skirt": "C",
    "Soiled Loincloth": "F",
    "Soldier's Crossbow": "C",
    "Spear": "B",
    "Spear of the Impaler": "S",
    "Spellblade's Gloves": "C",
    "Spellblade's Pointed Hat": "C",
    "Spellblade's Traveling Attire": "C",
    "Spellblade's Trousers": "C",
    "Spiked Caestus": "B",
    "Spiked Club": "C",
    "Spiked Spear": "B",
    "Spiraltree Seal": "D",
    "Spirit Glaive": "C",
    "Spirit Sword": "C",
    "Spread Crossbow": "C",
    "St. Trina's Torch": "D",
    "Staff of Loss": "B",
    "Staff of the Avatar": "B",
    "Staff of the Great Beyond": "S",
    "Staff of the Guilty": "B",
    "Star Fist": "A",
    "Star-Lined Sword": "A",
    "Stars of Ruin": "S",
    "Starscourge Greatsword": "S",
    "Steel-Wire Torch": "D",
    "Stone Club": "B",
    "Stone-Sheathed Sword": "F",
    "Stormhawk Axe": "B",
    "Swift Spear": "C",
    "Sword Lance": "S",
    "Sword of Darkness": "B",
    "Sword of Light": "B",
    "Sword of Milos": "A",
    "Sword of Night": "B",
    "Sword of Night and Flame": "S",
    "Sword of St. Trina": "C",
    "Thiollier's Garb": "C",
    "Thiollier's Gloves": "C",
    "Thiollier's Hidden Needle": "C",
    "Thiollier's Mask": "C",
    "Thiollier's Trousers": "C",
    "Thorned Whip": "C",
    "Tooth Whip": "F",
    "Torch": "D",
    "Torchpole": "C",
    "Traveler's Boots": "D",
    "Traveler's Clothes": "D",
    "Traveler's Gloves": "D",
    "Traveler's Hat": "D",
    "Traveler's Manchettes": "D",
    "Traveler's Slops": "D",
    "Traveling Maiden Boots": "B",
    "Traveling Maiden Gloves": "B",
    "Traveling Maiden Hood": "B",
    "Traveling Maiden Robe": "B",
    "Tree Sentinel Armor": "S",
    "Tree Sentinel Gauntlets": "S",
    "Tree Sentinel Greaves": "S",
    "Tree Sentinel Helm": "S",
    "Treespear": "A",
    "Troll Knight's Sword": "B",
    "Troll's Golden Sword": "B",
    "Troll's Hammer": "A",
    "Twinblade": "B",
    "Twinned Armor": "A",
    "Twinned Gauntlets": "A",
    "Twinned Greaves": "A",
    "Twinned Helm": "A",
    "Twinned Knight Swords": "B",
    "Uchigatana": "S",
    "Unendurable Frenzy": "A",
    "Urumi": "A",
    "Vagabond Knight Armor": "B",
    "Vagabond Knight Gauntlets": "B",
    "Vagabond Knight Greaves": "B",
    "Vagabond Knight Helm": "B",
    "Varré's Bouquet": "D",
    "Velvet Sword of St. Trina": "C",
    "Venomous Fang": "A",
    "Verdigris Armor": "S",
    "Verdigris Gauntlets": "S",
    "Verdigris Greatshield": "A",
    "Verdigris Greaves": "S",
    "Verdigris Helm": "S",
    "Veteran's Armor": "S",
    "Veteran's Gauntlets": "S",
    "Veteran's Greaves": "S",
    "Veteran's Helm": "S",
    "Veteran's Prosthesis": "B",
    "Vulgar Militia Armor": "A",
    "Vulgar Militia Gauntlets": "A",
    "Vulgar Militia Greaves": "A",
    "Vulgar Militia Helm": "A",
    "Vulgar Militia Saw": "B",
    "Vulgar Militia Shotel": "C",
    "Vyke's War Spear": "A",
    "Wakizashi": "A",
    "War Surgeon Gloves": "B",
    "War Surgeon Gown (Altered)": "B",
    "War Surgeon Trousers": "B",
    "Warhawk's Talon": "B",
    "Warped Axe": "C",
    "Warpick": "C",
    "Watchdog's Greatsword": "B",
    "Watchdog's Staff": "B",
    "Weathered Straight Sword": "C",
    "Whip": "B",
    "White Reed Armor": "A",
    "White Reed Gauntlets": "A",
    "White Reed Greaves": "A",
    "Wing of Astel": "S",
    "Winged Greathorn": "A",
    "Winged Scythe": "A",
    "Wise Man's Mask": "D",
    "Wolf Crest Shield": "D",
    "Young Lion's Armor": "B",
    "Young Lion's Gauntlets": "B",
    "Young Lion's Greaves": "B",
    "Young Lion's Helm": "B",
    "Zamor Armor": "D",
    "Zamor Bracelets": "D",
    "Zamor Curved Sword": "B",
    "Zamor Legwraps": "D",
    "Zamor Mask": "D",
    "Zweihander": "A",
}

# Trim threshold: an item counts as "bad" if its tier is in this set (C and below).
BAD_TIERS = frozenset({"C", "D", "F"})

# Remoteness score (see EldenRing._remoteness) >= this counts as "out of the way".
REMOTE_THRESHOLD = 3

# Sets/items kept despite a low tier (fashion / Alaric curation, 2026-06-14):
# Malenia's + Snow Witch armor are intentionally not trimmed.
TIER_KEEP_PREFIXES = ("Malenia's", "Snow Witch")
