# -*- coding: utf-8 -*-
"""AUTO-GENERATED. Low-value GOODS treated as junk filler by the check-trim pass
(SPEC-check-trim.md): cookbooks (recipe unlocks), greases (buff consumables), and
crafting materials (EquipParamGoods.goodsType==2). Smithing stones (type 14), glovewort,
spells, spirit ashes, tears, bell bearings and key items are deliberately NOT here."""

JUNK_GOODS = frozenset({
    'Aeonian Butterfly',
    'Albinauric Bloodclot',
    'Altus Bloom',
    "Ancient Dragon Apostle's Cookbook [1]",
    "Ancient Dragon Apostle's Cookbook [2]",
    "Ancient Dragon Apostle's Cookbook [3]",
    "Ancient Dragon Apostle's Cookbook [4]",
    "Ancient Dragon Knight's Cookbook [1]",
    "Ancient Dragon Knight's Cookbook [2]",
    "Antiquity Scholar's Cookbook [1]",
    "Antiquity Scholar's Cookbook [2]",
    "Armorer's Cookbook [1]",
    "Armorer's Cookbook [2]",
    "Armorer's Cookbook [3]",
    "Armorer's Cookbook [4]",
    "Armorer's Cookbook [5]",
    "Armorer's Cookbook [6]",
    "Armorer's Cookbook [7]",
    'Arteria Leaf',
    "Battlefield Priest's Cookbook [1]",
    "Battlefield Priest's Cookbook [2]",
    "Battlefield Priest's Cookbook [3]",
    "Battlefield Priest's Cookbook [4]",
    'Beast Blood',
    'Beast Horn',
    'Beast Liver',
    'Black Pyrefly',
    'Blessed Bone Shard',
    'Blood Grease',
    'Blood-Tainted Excrement',
    'Bloodrose',
    'Budding Cave Moss',
    'Budding Horn',
    'Cave Moss',
    'Congealed Putrescence',
    'Crab Eggs',
    'Cracked Crystal',
    'Crystal Bud',
    'Crystal Cave Moss',
    'Deep-Purple Lily',
    'Dewgem',
    'Dewkissed Herba',
    'Dragon Communion Grease',
    "Dragon's Calorbloom",
    'Dragonbolt Grease',
    'Dragonwound Grease',
    'Drawstring Blood Grease',
    'Drawstring Fire Grease',
    'Drawstring Golden Grease',
    'Drawstring Holy Grease',
    'Drawstring Lightning Grease',
    'Drawstring Messmerfire Grease',
    'Drawstring Poison Grease',
    'Drawstring Royal Magic Grease',
    'Ember of Messmer',
    'Empyrean-Blood Burgeon',
    'Erdleaf Flower',
    'Eye of Yelough',
    'Faded Erdleaf Flower',
    'Festive Grease',
    "Fevor's Cookbook [1]",
    "Fevor's Cookbook [2]",
    "Fevor's Cookbook [3]",
    'Finger Mimic',
    "Finger-Weaver's Cookbook [1]",
    "Finger-Weaver's Cookbook [2]",
    'Fire Blossom',
    'Fire Grease',
    "Fire Knight's Cookbook [1]",
    "Fire Knight's Cookbook [2]",
    'Flight Pinion',
    'Fly Mold',
    'Forager Brood Cookbook [1]',
    'Forager Brood Cookbook [2]',
    'Forager Brood Cookbook [3]',
    'Forager Brood Cookbook [4]',
    'Forager Brood Cookbook [5]',
    'Forager Brood Cookbook [6]',
    'Forager Brood Cookbook [7]',
    'Formic Rock',
    'Four-Toed Fowl Foot',
    'Freezing Grease',
    "Frenzied's Cookbook [1]",
    "Frenzied's Cookbook [2]",
    'Frozen Maggot',
    'Fulgurbloom',
    'Furnace Visage',
    'Gas Stone',
    'Ghostflame Bloom',
    'Glintslab Firefly',
    "Glintstone Craftsman's Cookbook [1]",
    "Glintstone Craftsman's Cookbook [2]",
    "Glintstone Craftsman's Cookbook [3]",
    "Glintstone Craftsman's Cookbook [4]",
    "Glintstone Craftsman's Cookbook [5]",
    "Glintstone Craftsman's Cookbook [6]",
    "Glintstone Craftsman's Cookbook [7]",
    "Glintstone Craftsman's Cookbook [8]",
    'Glintstone Firefly',
    'Gold Firefly',
    'Gold-Tinged Excrement',
    'Golden Centipede',
    'Golden Rowa',
    'Golden Sunflower',
    'Grave Cricket',
    "Grave Keeper's Brainpan",
    "Grave Keeper's Cookbook [1]",
    "Grave Keeper's Cookbook [2]",
    'Grave Violet',
    'Gravel Stone',
    'Great Dragonfly Head',
    "Greater Potentate's Cookbook [10]",
    "Greater Potentate's Cookbook [11]",
    "Greater Potentate's Cookbook [12]",
    "Greater Potentate's Cookbook [13]",
    "Greater Potentate's Cookbook [14]",
    "Greater Potentate's Cookbook [1]",
    "Greater Potentate's Cookbook [2]",
    "Greater Potentate's Cookbook [3]",
    "Greater Potentate's Cookbook [4]",
    "Greater Potentate's Cookbook [5]",
    "Greater Potentate's Cookbook [6]",
    "Greater Potentate's Cookbook [7]",
    "Greater Potentate's Cookbook [8]",
    "Greater Potentate's Cookbook [9]",
    'Hefty Beast Bone',
    'Herba',
    'Holy Grease',
    'Horn-Strewn Excrement',
    'Human Bone Shard',
    "Igon's Cookbook [1]",
    "Igon's Cookbook [2]",
    'Knot Resin',
    'Land Octopus Ovary',
    'Lightning Grease',
    'Living Jar Shard',
    "Loyal Knight's Cookbook",
    'Lump of Flesh',
    "Mad Craftsman's Cookbook [1]",
    "Mad Craftsman's Cookbook [2]",
    "Mad Craftsman's Cookbook [3]",
    'Magic Grease',
    'Melted Mushroom',
    'Messmerfire Grease',
    "Miquella's Lily",
    'Miranda Powder',
    "Missionary's Cookbook [1]",
    "Missionary's Cookbook [2]",
    "Missionary's Cookbook [3]",
    "Missionary's Cookbook [4]",
    "Missionary's Cookbook [5]",
    "Missionary's Cookbook [6]",
    "Missionary's Cookbook [7]",
    'Mushroom',
    'Nailstone',
    'Nascent Butterfly',
    'Nectarblood Burgeon',
    "Nomadic Warrior's Cookbook [10]",
    "Nomadic Warrior's Cookbook [11]",
    "Nomadic Warrior's Cookbook [12]",
    "Nomadic Warrior's Cookbook [13]",
    "Nomadic Warrior's Cookbook [14]",
    "Nomadic Warrior's Cookbook [15]",
    "Nomadic Warrior's Cookbook [16]",
    "Nomadic Warrior's Cookbook [17]",
    "Nomadic Warrior's Cookbook [18]",
    "Nomadic Warrior's Cookbook [19]",
    "Nomadic Warrior's Cookbook [1]",
    "Nomadic Warrior's Cookbook [20]",
    "Nomadic Warrior's Cookbook [21]",
    "Nomadic Warrior's Cookbook [22]",
    "Nomadic Warrior's Cookbook [23]",
    "Nomadic Warrior's Cookbook [24]",
    "Nomadic Warrior's Cookbook [2]",
    "Nomadic Warrior's Cookbook [3]",
    "Nomadic Warrior's Cookbook [4]",
    "Nomadic Warrior's Cookbook [5]",
    "Nomadic Warrior's Cookbook [6]",
    "Nomadic Warrior's Cookbook [7]",
    "Nomadic Warrior's Cookbook [8]",
    "Nomadic Warrior's Cookbook [9]",
    'Old Fang',
    'Pearlescent Scale',
    "Perfumer's Cookbook [1]",
    "Perfumer's Cookbook [2]",
    "Perfumer's Cookbook [3]",
    "Perfumer's Cookbook [4]",
    'Poison Grease',
    'Poisonbloom',
    'Rada Fruit',
    'Rauh Burrow',
    'Red Fulgurbloom',
    'Redflesh Mushroom',
    'Rimed Crystal Bud',
    'Rimed Rowa',
    'Root Resin',
    'Rot Grease',
    'Rowa Fruit',
    'Royal Magic Grease',
    'Sacramental Bud',
    'Sanctuary Stone',
    'Sanguine Amaryllis',
    'Scarlet Bud',
    'Scorpion Liver',
    'Shadow Sunflower',
    'Sharp Gravel Stone',
    'Shield Grease',
    'Silver Firefly',
    'Silver Tear Husk',
    'Sliver of Meat',
    'Slumbering Egg',
    'Smoldering Butterfly',
    'Soporific Grease',
    'Spirit Calculus',
    'Spiritgrave Stone',
    "St. Trina Disciple's Cookbook [1]",
    "St. Trina Disciple's Cookbook [2]",
    "St. Trina Disciple's Cookbook [3]",
    'Stormhawk Feather',
    'String',
    'Strip of White Flesh',
    'Swollen Grape',
    'Tarnished Golden Sunflower',
    'Thin Beast Bones',
    "Tibia's Cookbook",
    'Toxic Mossling',
    'Toxic Mushroom',
    "Trina's Lily",
    'Turtle Neck Meat',
    'Volcanic Stone',
    'Whiteflesh Mushroom',
    'Winter-Lantern Fly',
    'Yellow Ember',
    'Yellow Fulgurbloom',
})
